### ISSUE TITLE
Why the SDR images looks better than the HDR images

### ISSUE THREAD

**Issue by jchhuang** [AndreGuo/HDRTVDM#5]
Hello Dr. Guo, We are interested in your work, however, when we download the datasets and observe the images in the screen with HDR format support, we find that the SDR images looks better than the HDR images. This phenomena is very confusing, may you help to explain. Thanks a lot.
For example, the HDR image in the following screenshot looks more dimmer and colorless than the SDR
![example](https://github.com/AndreGuo/HDRTVDM/assets/16332360/b8321407-6e31-49df-ba37-a26098ee1dc1)

**Comment by AndreGuo** [comment]
HDR/WCG has bigger luminance and color container.
So, the corresponding normalized pixel value of the same real luminance and color will appear larger in SDR than HDR/WCG. (e.g. 100nit is Y=1 SDR, while Y≈0.58 in PQ HDR). In this case, if you show these two SDR and HDR/WCG (recording same scene luminance and color) by same SDR display, pixel value Y=1 will be interpreted by 100% luminance display capacity, while Y≈0.58 in HDR will only be interpreted by e.g. 58% capacity and thus appears dimmer.
The same goes for color, same scene color will have smaller normalized pixel value in WCG (e.g. BT.2020) than CCG (BT.709/sRGB), so if they are simultaneously displayed by same BT.709/sRGB display, WCG image will appear more desaturated.
The HDR/WCG image in HDR-SDR pairs in our dataset will always look dimmer and more desaturated, if interpreted at same display (no matter what display you use, just because HDR/WCG has smaller normalized pixel value). And if you want a correct look, please display them separately by sRGB/SDR and HDR/WCG display.

**Comment by whyb** [comment]
> Hello Dr. Guo, We are interested in your work, however, when we download the datasets and observe the images in the screen with HDR format support, we find that the SDR images looks better than the HDR images. This phenomena is very confusing, may you help to explain. Thanks a lot. For example, the HDR image in the following screenshot looks more dimmer and colorless than the SDR ![example](https://github.com/AndreGuo/HDRTVDM/assets/16332360/b8321407-6e31-49df-ba37-a26098ee1dc1)

I am trying this model and uploaded a SDR/HDR comparison picture, you can try it. https://whyb.github.io/HDRTVDM-onnx/
